### ISSUE TITLE
Error with two MiAirPurifier2S

### ISSUE THREAD

**Issue by gaoyifan** [YinHangCode/homebridge-mi-airpurifier#19]
Hi,

I'd like to report a problem. It works well with only one MiAirPurifier2S. But when adding another MiAirPurifier2S to `config.json` , homebridge compains that `Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 82cd607a-98dc-4432-b06d-6dc29ebe2118`.

Could you please check the problem?

Full log:
```
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: HOMEBRIDGE_AUTO_UPDATE_NPM_MODULES=on (default value)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loaded config.json with 0 accessories and 3 platforms.
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] ---
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loaded plugin: homebridge-info
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Registering platform 'homebridge-info.Info'
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] ---
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loaded plugin: homebridge-mi-acpartner
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Registering platform 'homebridge-mi-acpartner.XiaoMiAcPartner'
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] ---
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loaded plugin: homebridge-mi-airpurifier
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Registering platform 'homebridge-mi-airpurifier.MiAirPurifierPlatform'
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] ---
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loaded plugin: homebridge-mi-aqara
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Registering platform 'homebridge-mi-aqara.MiAqaraPlatform'
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] ---
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loaded plugin: homebridge-server
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Registering platform 'homebridge-server.Server'
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] ---
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] Loading 3 platforms...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [Homebridge Info Server] Initializing Info platform...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [Homebridge Server] Initializing Server platform...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing MiAirPurifierPlatform platform...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]*******************************************************************
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]          MiAirPurifierPlatform v0.1.3 By YinHang
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-airpurifier
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]                                              QQ Group: 107927710
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]*******************************************************************
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]start success...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]device size: 2, accessories size: 8
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing platform accessory 'MiAirPurifier2S'...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BB-0000-1000-8000-0026BB765291. Adding anyway.
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing platform accessory 'MiAirPurifier2S Temperature'...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing platform accessory 'MiAirPurifier2S Humidity'...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing platform accessory 'MiAirPurifier2S AirQuality'...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing platform accessory 'weida de MiAirPurifier2S'...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: HAP Warning: Characteristic 000000AC-0000-1000-8000-0026BB765291 not in required or optional characteristics for service 000000BB-0000-1000-8000-0026BB765291. Adding anyway.
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: [2018-8-27 23:08:06] [MiAirPurifierPlatform] Initializing platform accessory 'MiAirPurifier2S Temperature'...
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: /var/snap/homebridge/common/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: ^
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 82cd607a-98dc-4432-b06d-6dc29ebe2118
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Bridge.Accessory.addBridgedAccessory (/var/snap/homebridge/common/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:264:13)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Server.<anonymous> (/var/snap/homebridge/common/lib/node_modules/homebridge/lib/server.js:398:24)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at /var/snap/homebridge/common/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at MiAirPurifierPlatform.accessories (/var/snap/homebridge/common/lib/node_modules/homebridge-mi-airpurifier/index.js:109:9)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Server._loadPlatformAccessories (/var/snap/homebridge/common/lib/node_modules/homebridge/lib/server.js:385:20)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Server._loadPlatforms (/var/snap/homebridge/common/lib/node_modules/homebridge/lib/server.js:329:16)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Server.run (/var/snap/homebridge/common/lib/node_modules/homebridge/lib/server.js:85:36)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at module.exports (/var/snap/homebridge/common/lib/node_modules/homebridge/lib/cli.js:43:10)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Object.<anonymous> (/var/snap/homebridge/common/lib/node_modules/homebridge/bin/homebridge:17:22)
Aug 27 23:08:06 hostname homebridge.homebridge[13825]: at Module._compile (module.js:652:30)
```

config:
```
{
    "bridge": {
        "name": "Homebridge",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },

    "description": "HomeBridge@USTC908",

    "platforms": [
     {
         "platform": "Info",
         "port": 9876,
         "name": "Homebridge Info Server",
         "updateFrequency": 10000,
         "updateCheckFrequency": 86400
     },
     {
         "platform": "Server",
         "port"    : 8765,
         "name"    : "Homebridge Server",
         "log"     : "/var/snap/homebridge/current/serber.log",
         "restart" : "snapctl restart homebridge.homebridge"
     },
     {
         "platform": "MiAirPurifierPlatform",
         "deviceCfgs": [
         {
             "type": "MiAirPurifier2S",
             "ip": "100.66.1.152",
             "token": "****",
             "airPurifierDisable": false,
             "airPurifierName": "MiAirPurifier2S",
             "silentModeSwitchDisable": false,
             "silentModeSwitchName": "MiAirPurifier2S Silent Mode Switch",
             "temperatureDisable": false,
             "temperatureName": "MiAirPurifier2S Temperature",
             "humidityDisable": false,
             "humidityName": "MiAirPurifier2S Humidity",
             "buzzerSwitchDisable": true,
             "buzzerSwitchName": "MiAirPurifier2S Buzzer Switch",
             "ledBulbDisable": true,
             "ledBulbName": "MiAirPurifier2S LED Switch",
             "airQualityDisable": false,
             "airQualityName": "MiAirPurifier2S AirQuality"
         }, {
             "type": "MiAirPurifier2S",
             "ip": "100.66.1.156",
             "token": "****",
             "airPurifierDisable": false,
             "airPurifierName": "weida de MiAirPurifier2S",
             "silentModeSwitchDisable": false,
             "silentModeSwitchName": "MiAirPurifier2S Silent Mode Switch",
             "temperatureDisable": false,
             "temperatureName": "MiAirPurifier2S Temperature",
             "humidityDisable": false,
             "humidityName": "MiAirPurifier2S Humidity",
             "buzzerSwitchDisable": true,
             "buzzerSwitchName": "MiAirPurifier2S Buzzer Switch",
             "ledBulbDisable": true,
             "ledBulbName": "MiAirPurifier2S LED Switch",
             "airQualityDisable": false,
             "airQualityName": "MiAirPurifier2S AirQuality"
         }
         ]
     }
    ]
}
```

**Comment by kinochanon** [comment]
I'm having a similar issue. Is there a fix for this?
