### ISSUE TITLE
UUID error

### ISSUE THREAD

**Issue by mfoll** [YinHangCode/homebridge-mi-airpurifier#3]
Hi,

When I add a second device, I get the following error:
```
[2017-10-16 14:59:25] [MiAirPurifierPlatform] Initializing MiAirPurifierPlatform platform...
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]*******************************************************************
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]          MiAirPurifierPlatform v0.0.8 By YinHang
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]  GitHub: https://github.com/YinHangCode/homebridge-mi-airpurifier 
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]                                              QQ Group: 107927710  
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]*******************************************************************
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]start success...
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][DEBUG]Initializing AirPurifierPro device: 192.168.1.31, accessories size: 4
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][DEBUG]Initializing AirPurifier2 device: 192.168.1.2, accessories size: 4
[2017-10-16 14:59:25] [MiAirPurifierPlatform] [MiAirPurifierPlatform][INFO]device size: 2, accessories size: 8
[2017-10-16 14:59:25] [MiAirPurifierPlatform] Initializing platform accessory 'AirPurifier'...
[2017-10-16 14:59:25] [MiAirPurifierPlatform] Initializing platform accessory 'Temperature'...
[2017-10-16 14:59:25] [MiAirPurifierPlatform] Initializing platform accessory 'Humidity'...
[2017-10-16 14:59:25] [MiAirPurifierPlatform] Initializing platform accessory 'AirQuality'...
[2017-10-16 14:59:25] [MiAirPurifierPlatform] Initializing platform accessory 'AirPurifier'...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257
      throw new Error("Cannot add a bridged Accessory with the same UUID as another bridged Accessory: " + existing.UUID);
      ^

Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: 80916c4a-8d56-4e91-97ad-6e5a69c1a994
    at Bridge.Accessory.addBridgedAccessory (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:257:13)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:367:24)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:16:19
    at MiAirPurifierPlatform.accessories (/usr/local/lib/node_modules/homebridge-mi-airpurifier/index.js:104:9)
    at Server._loadPlatformAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:354:20)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:298:16)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:569:30)
```

Making all the names unique solves the issue, like for example:
```
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'AirPurifier'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'Temperature'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'Humidity'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'AirQuality'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'AirPurifier2'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'Temperature2'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'Humidity2'...
[2017-10-16 15:02:42] [MiAirPurifierPlatform] Initializing platform accessory 'AirQuality2'...
```

Any help would be appreciated!

**Comment by chao** [comment]
I have the same issue with you, do you have two air purifiers? you need to give every accessory an unique name.

**Comment by YinHangCode** [comment]
UUID is generated by name. Please use different names.
